#
# Makefile for the apex driver
#

ds-objs := ds_generic.o ds_interrupt.o ds_page_table.o ds_sysfs.o ds_ioctl.o
obj-$(CONFIG_DS)              += ds.o

dwn-objs := apex_driver.o
obj-$(CONFIG_DWN)             += dwn.o
