obj-$(CONFIG_IPA)	+=	ipa.o

ipa-y			:=	ipa_main.o ipa_dp.o \
				ipa_client.o ipa_utils.o ipa_interrupts.o \
				ipa_uc.o gsi.o rmnet_ipa.o \
				ipa_qmi.o ipa_qmi_msg.o \
				ipahal.o ipahal_reg.o ipahal_fltrt.o
