obj-$(CONFIG_SECURITY_CHROMIUMOS) += inode_mark.o lsm.o securityfs.o utils.o
obj-$(CONFIG_SECURITY_CHROMIUMOS) += jail_control.o jail_device.o jail_request.o
obj-$(CONFIG_ALT_SYSCALL_CHROMIUMOS) += alt-syscall.o
